### ISSUE TITLE
feature request: use js git lib instead of relying on system git

### ISSUE THREAD

**Issue by sanzoghenzo** [silverbulletmd/silverbullet-git#9]
this will make the plug independent from the host system.

From a quick look, it seems that [isomorphic-git](https://isomorphic-git.org/en/) could do the job.

My use case: silverbullet is installed on a server in my homelab, which doesn't have git installed, and I would like to avoid to install it just for this.

Would you consider this, and/or are you open to accept PRs (if I could find the time to do it myself)?

**Comment by sanzoghenzo** [comment]
As a side note, I got no error messages if I run the clone/sync command on my installation; should I open a bug report for that, regardless of this feature request?

**Comment by zefhemel** [comment]
I wouldn't add this to the core of SilverBullet because it would simply add to much weight to the entire distribution for everybody to serve  a very small user niche. As far as I can estimate by far most people run SilverBullet using the supplied docker container which has git pre-installed, I assume you're running the Deno distribution directly?

**Comment by zefhemel** [comment]
And this cannot really be built into the plug (because it's too much of a sandboxed environment), it'd have to be built into SilverBullet core.

**Comment by sanzoghenzo** [comment]
Undestood, thanks for taking a look at it anyway.

> I assume you're running the Deno distribution directly?

Correct, I'm running a NixOS server that provides a systemd service to run silverbullet directly in deno.

I'll add git to my system then
